let data={generatedAt:new Date().toISOString(),agents:[],missions:[]};let team=null,agent=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const teamIcon=t=>({"Bâtiment":"⌂","Voirie":"▥","Espaces verts":"●","Propreté":"♣","Festivités":"✦","DMT":"◆","Moyens techniques":"◆"}[t]||"•");
const fmt=d=>d?new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date(d+"T12:00:00")):"";
const agentName=id=>data.agents.find(a=>String(a.id)===String(id))?.name||id;
function normalize(r){return{generatedAt:r.generatedAt||new Date().toISOString(),agents:Array.isArray(r.agents)?r.agents:[],missions:Array.isArray(r.missions)?r.missions:[]}}
async function load(){try{const r=await fetch("Charli_Consultation.json?ts="+Date.now(),{cache:"no-store"});if(r.ok)data=normalize(await r.json())}catch(e){}document.querySelector("#updated").textContent=new Date(data.generatedAt).toLocaleString("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});route()}
function teams(){const preferred=["Bâtiment","Voirie","Espaces verts","Propreté","Festivités","DMT","Moyens techniques"];const found=[...new Set([...data.agents.map(a=>a.team),...data.missions.map(m=>m.team)].filter(Boolean))];return [...preferred.filter(x=>found.includes(x)),...found.filter(x=>!preferred.includes(x))]}
function home(){team=null;agent=null;document.querySelector("#view").innerHTML=`<div class="intro"><h2>Choisir une équipe</h2><p>Sélectionnez l'équipe dont vous souhaitez consulter le planning.</p></div><div class="grid"><button class="choice all" data-team="__ALL__"><span class="ico">▦</span><b>Toutes les équipes</b><small>Afficher le planning général</small></button>${teams().map(t=>`<button class="choice" data-team="${esc(t)}"><span class="ico">${teamIcon(t)}</span><b>${esc(t)}</b><small>${data.agents.filter(a=>a.team===t).length} agent(s)</small></button>`).join("")}</div>`;document.querySelectorAll("[data-team]").forEach(b=>b.onclick=()=>{team=b.dataset.team;if(team==="__ALL__")showPlanning();else showAgents()})}
function showAgents(){const aa=data.agents.filter(a=>a.team===team);document.querySelector("#view").innerHTML=`<div class="toolbar"><button class="back" id="back">← Équipes</button><div class="context"><b>${esc(team)}</b><small>Choisir un agent</small></div></div><div class="intro"><h2>Qui souhaitez-vous afficher ?</h2><p>Vous pouvez consulter toute l'équipe ou un agent en particulier.</p></div><div class="agentlist"><button class="agent all" data-agent="__ALL__"><b>Toute l'équipe</b><small>Planning collectif ${esc(team)}</small></button>${aa.map(a=>`<button class="agent" data-agent="${esc(a.id)}"><b>${esc(a.name)}</b><small>${esc(a.role||a.team||"")}</small></button>`).join("")}</div>`;document.querySelector("#back").onclick=home;document.querySelectorAll("[data-agent]").forEach(b=>b.onclick=()=>{agent=b.dataset.agent;showPlanning()})}
function mondayOfReference(){const ref=new Date(data.generatedAt||Date.now()),d=new Date(ref.getFullYear(),ref.getMonth(),ref.getDate(),12),day=d.getDay(),delta=day===0?-6:1-day;d.setDate(d.getDate()+delta);return d}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function filtered(){return data.missions.filter(m=>(team==="__ALL__"||!team||m.team===team)&&(agent==="__ALL__"||!agent||(m.agents||[]).map(String).includes(String(agent))))}
function missionCard(m){const urgent=(m.priority||"").toLowerCase().includes("urgent"),watch=!!(m.watchLevel||m.watchNote);return `<a class="mission ${urgent?"urgent":watch?"watch":""}" href="#mission=${encodeURIComponent(m.id)}"><div class="missiontop"><b>${esc(m.title||"Mission")}</b><span>›</span></div><small>📍 ${esc(m.location||"Lieu non renseigné")}</small><small>${esc(m.slot||"")}${m.startTime?" • "+esc(m.startTime):""}${m.duration?" • "+esc(m.duration)+" h":""}</small><div class="badges">${urgent?`<span class="pill red">Urgente</span>`:""}${watch?`<span class="pill amber">${esc(m.watchLevel||"Vigilance")}</span>`:""}<span class="pill">${esc(m.status||"À faire")}</span></div></a>`}
function showPlanning(){const ms=filtered(),mon=mondayOfReference(),days=Array.from({length:5},(_,i)=>{const x=new Date(mon);x.setDate(mon.getDate()+i);return iso(x)});const label=team==="__ALL__"?"Toutes les équipes":agent&&agent!=="__ALL__"?agentName(agent):team;document.querySelector("#view").innerHTML=`<div class="toolbar"><button class="back" id="back">← Choix</button><div class="context"><b>${esc(label||"Planning")}</b><small>Semaine du ${new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long"}).format(mon)}</small></div></div><h2 class="weektitle">Planning de la semaine</h2>${days.map(d=>{const dm=ms.filter(m=>m.date===d);return `<section class="day"><div class="dayhead">${fmt(d)}</div>${dm.length?dm.map(missionCard).join(""):`<div class="empty">Aucune mission prévue</div>`}</section>`}).join("")}<div class="note">Consultation uniquement • Les informations proviennent de Charli STM.</div>`;document.querySelector("#back").onclick=()=>team&&team!=="__ALL__"?showAgents():home}
function missionDetail(id){const m=data.missions.find(x=>String(x.id)===String(id));if(!m){showPlanning();return}const names=(m.agents||[]).map(agentName).filter(Boolean).join(", ");const hasProgress=m.progress!==null&&m.progress!==undefined&&m.progress!==""&&!Number.isNaN(Number(m.progress));const p=hasProgress?Math.max(0,Math.min(100,Number(m.progress))):null;document.querySelector("#view").innerHTML=`<button class="back" id="back">← Planning</button><section class="detailhero"><small>${esc(m.team||"")}</small><h2>${esc(m.title||"Mission")}</h2><div class="badges"><span class="pill">${esc(m.status||"À faire")}</span>${(m.priority||"").toLowerCase().includes("urgent")?`<span class="pill red">Urgente</span>`:""}${m.watchLevel?`<span class="pill amber">${esc(m.watchLevel)}</span>`:""}</div>${hasProgress?`<div class="progress"><i style="width:${p}%"></i></div><small>${p}% d'avancement</small>`:""}</section><section class="detailsection"><h3>Informations</h3><div class="fields">${field("Date",fmt(m.date))}${field("Créneau",[m.slot,m.startTime].filter(Boolean).join(" • "))}${field("Lieu",m.location)}${field("Activité",m.activity)}${field("Agents",names,true)}${field("Durée",m.duration?m.duration+" h":"")}${field("N° BT",m.bt)}${field("Demandeur",m.requester)}</div></section>${m.description?section("Description",m.description):""}${m.report?section("Compte rendu",m.report):""}${m.watchNote?section("Vigilance / suivi prioritaire",m.watchNote):""}${m.nextStep?section("Prochaine étape",m.nextStep):""}${m.decision?section("Décision",m.decision):""}${m.terrainProblem||m.terrainProblemReport?section("Problème signalé",m.terrainProblemReport||m.terrainComment||"Problème signalé sur le terrain"):""}`;document.querySelector("#back").onclick=()=>{history.replaceState(null,"",location.pathname+location.search);showPlanning()}}
function field(k,v,wide=false){return v?`<div class="field ${wide?"wide":""}"><small>${esc(k)}</small><div>${esc(v)}</div></div>`:""}function section(t,v){return `<section class="detailsection"><h3>${esc(t)}</h3><div class="field wide"><div>${esc(v)}</div></div></section>`}
function route(){const h=location.hash||"";if(h.startsWith("#mission=")){missionDetail(decodeURIComponent(h.slice(9)));return}home()}
window.addEventListener("hashchange",()=>{const h=location.hash||"";if(h.startsWith("#mission="))missionDetail(decodeURIComponent(h.slice(9)))});load();
